---
title: "In-class_Ex12"
author: "Ryan"
date: "November 11, 2024"
date-modified: "last-modified"
format: html
editor: visual
---



```{r}
pacman::p_load(sf, spdep, GWmodel, SpatialML, 
               tmap, rsample, Metrics, tidyverse, ggstatsplot)
```

```{r}
mdata <- read_rds("data/rds/mdata.rds")
```

```{r}
set.seed(1234)
HDB_sample <- mdata %>%
  sample_n(1500)
```

```{r}
overlapping_points <- HDB_sample %>%
  mutate(overlap = lengths(st_equals(., .)) > 1)
summary(overlapping_points$overlap)
```

```{r}
HDB_sample <- HDB_sample %>%
  st_jitter(amount = 5)
```


```{r}
set.seed(1234)
resale_split <- initial_split(HDB_sample, 
                              prop = 6.67/10,)
train_data <- training(resale_split)
test_data <- testing(resale_split)
```



```{r}
#| fig-width: 10
#| fig-height: 12
mdata_nogeo <- mdata %>%
  st_drop_geometry()
ggcorrmat(mdata_nogeo[, 2:17])
```

```{r}
price_mlr <- lm(resale_price ~ floor_area_sqm +
                  storey_order + remaining_lease_mths +
                  PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER +
                  PROX_MRT + PROX_PARK + PROX_MALL + 
                  PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN +
                  WITHIN_350M_CHILDCARE + WITHIN_350M_BUS +
                  WITHIN_1KM_PRISCH,
                data=train_data)
olsrr::ols_regress(price_mlr)
```

```{r}
gwr_bw_train_ad <- bw.gwr(resale_price ~ floor_area_sqm +
                  storey_order + remaining_lease_mths +
                  PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER +
                  PROX_MRT + PROX_PARK + PROX_MALL + 
                  PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN +
                  WITHIN_350M_CHILDCARE + WITHIN_350M_BUS +
                  WITHIN_1KM_PRISCH,
                data=train_data,
                approach="CV",
                kernel="gaussian",
                adaptive=TRUE,
                longlat=FALSE)
```

```{r}
gwr_ad <- gwr.basic(formula = resale_price ~ floor_area_sqm +
                  storey_order + remaining_lease_mths +
                  PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER +
                  PROX_MRT + PROX_PARK + PROX_MALL + 
                  PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN +
                  WITHIN_350M_CHILDCARE + WITHIN_350M_BUS +
                  WITHIN_1KM_PRISCH,
                data=train_data,
                bw=20,
                kernel="gaussian",
                adaptive=TRUE,
                longlat=FALSE)
```

```{r}
#| eval: false
gwr_pred_df <- as.data.frame(
  gwr_pred$SDF$prediction) %>%
  rename(gwr_pred = "gwr_pred$SDF$prediction")
```

```{r}
#| eval: false
coords <- st_coordinates(HDB_sample)
coords_train <- st_coordinates(train_data)
coords_test <- st_coordinates(test_data)
```

```{r}
#| eval: false
train_data_nogeom <- train_data %>% 
  st_drop_geometry()
```

```{r}
#| eval: false
set.seed(1234)
rf <- ranger(resale_price ~ floor_area_sqm +
              storey_order + remaining_lease_mths +
              PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER +
              PROX_MRT + PROX_PARK + PROX_MALL + 
              PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN +
              WITHIN_350M_CHILDCARE + WITHIN_350M_BUS +
              WITHIN_1KM_PRISCH,
            data=train_data_nogeom)
```

```{r}
#| eval: false
test_data_nogeom <- cbind(
  test_data, coords_test) %>%
  st_drop_geometry()
```

```{r}
#| eval: false
rf_pred <- predict(rf,
                  data = test_data_nogeom)
```

```{r}
#| eval: false
rf_pred_df <- as.data.frame(rf_pred) %>%
  rename(rf_pred = "rf_pred$predictions")
```

```{r}
#| eval: false
grf_ad <- grf(formula = resale_price ~ floor_area_sqm +
                  storey_order + remaining_lease_mths +
                  PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER +
                  PROX_MRT + PROX_PARK + PROX_MALL + 
                  PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN +
                  WITHIN_350M_CHILDCARE + WITHIN_350M_BUS +
                  WITHIN_1KM_PRISCH,
                data=train_data_nogeom,
                bw=20,
                kernel="adaptive",
                coords=coords_train)
```

```{r}
#| eval: false
grf_pred <- predict.grf(grf_ad,
                        test_data_nogeom,
                        x.var.name="X",
                        y.var.name="Y",
                        local.w=1,
                        global.w=0)
```

```{r}
#| eval: false
grf_pred_df <- as.data.frame(grf_pred)
```

```{r}
#| eval: false
test_data_pred <- test_data %>%
  dplyr::select(resale_price) %>%
  cbind(gwr_pred_df) %>% 
  cbind(rf_pred_df) %>%
  cbind(grf_pred_df)
```

```{r}
#| eval: false
test_longer <- test_data_pred %>%
  st_drop_geometry() %>%
  pivot_longer(cols = ends_with("pred"),
              names_to = "model",
              values_to = "predicted")
```

```{r}
#| eval: false
model_labels <- c(
  gwr_pred = "gwr",
  rf_pred = "Random Forest",
  grf_pred = "gwRF")

test_longer <- test_longer %>%
  mutate(model = recode(
    model, !!!model_labels))
```

```{r}
#| eval: false
rmse_results <- test_longer %>%
  group_by(model) %>%
  rmse(truth = resale_price,
      estimate = predicted) %>%
  rename(rmse = .estimate) %>%
  dplyr::select(model, rmse)
```

```{r}
#| eval: false
ggplot(rmse_results,
       aes(x = reorder(model, rmse),
           y = rmse,
           fill = "skyblue")) +
  geom_bar(stat = "identity",
          fill = "skyblue", 
          color = "black", 
          width = 0.7) +
  labs(title = "RMSE Comparison of Model",
      y = "RMSE", 
      x = "Model") +
  theme_minimal()
```

```{r}
#| eval: false
test_longer <- test_longer %>%
  left_join(rmse_results, by = "model")

ggplot(data = test_longer,
       aes(x = predicted, y = resale_price)) +
  facet_wrap(~ model) +
  geom_point() +
  geom_text(data = rmse_results, 
            aes(x = Inf, y = Inf,
                label = paste("RMSE: ", round(rmse, 2))),
            hjust = 1.1, vjust = 1.1, 
            color = "black", size = 4)

```

```{r}
#| eval: false
var_imp <- data.frame(
  Variable = names(grf_ad$Global.Model$variable.importance),
  Importance = grf_ad$Global.Model$vairable.importance
)
```

```{r}
#| eval: false
ggplot(var_imp, aes(x = reorder(Variable,
                              Importance),
                    y = Importance)) +
geom_bar(stat = "identity",
        fill = "skyblue") +
coord_flip() +
labs(
  title = "Variable Importance from Ranger Model",
  x = "Variables",
  y = "Importance"
) +
theme_minimal()
```
